### ISSUE TITLE
Provide sample

### ISSUE THREAD

**Issue by thusithathilina** [hyperledger/anoncreds-rs#250]
It would be really helpful to have some samples and getting started guide

**Comment by berendsliedrecht** [comment]
Hi. I think the documentation within the code has extensive examples on how to use this library. Since this library is not yet released, there is no docs.rs page, yet. Once it is, there will be a better way to view these examples. Also, you can take a look at the tests or usage in frameworks like ACA-Py and AFJ to see how it is used.

**Comment by TimoGlastra** [comment]
I think this is a valid issue @berendsliedrecht, and seeing how it should be used from AFJ / ACA-Py is quite complex. 

Some basic flow of what methods to call, in what order would be helpful. It could contain references to different languages, as the methods and input / output are almost exactly the same.

**Comment by berendsliedrecht** [comment]
Those flows are provided in the docs which will be available when the application is released. The codebase is full of examples like [this](https://github.com/hyperledger/anoncreds-rs/blob/62912bc1e7c041ad7e8a9221a74a6c8c9f2a6b4f/src/services/issuer.rs#L632-L700), which is more than sufficient imo.

**Comment by swcurran** [comment]
What does docs.rs get us?  Is it the docstrings from the code generated?

Is there sufficient material to produce a Mkdocs site from yet, or is documentation needed to be written?
